# Generated by Django 5.2.8 on 2025-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Люди', 'verbose_name_plural': 'Человек'},
        ),
    ]
