# Generated by Django 5.2.8 on 2025-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, help_text='возраст'),
        ),
    ]
