# Generated by Django 5.2.8 on 2025-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_application_alter_person_age_alter_person_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, default=0, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('user', 'Б/у')], default='new', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_car',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='ingine_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='application',
            name='car',
            field=models.CharField(max_length=75, verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
