# Generated by Django 5.2.8 on 2025-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_application_options_car_body_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='car',
            name='status_car',
            field=models.BooleanField(blank=True, choices=[('available', 'В наличии'), ('on_sale', 'В продаже'), ('sold', 'Продан')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, default=0, max_length=40, null=True, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('used', 'Б/у')], default='new', max_length=10, null=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_car',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='ingine_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Компанию'),
        ),
        migrations.AlterField(
            model_name='car',
            name='marka',
            field=models.CharField(max_length=10, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='VIN код'),
        ),
    ]
