# Generated by Django 5.2.8 on 2025-11-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_car_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status_car',
            field=models.CharField(blank=True, choices=[('available', 'В наличии'), ('on_sale', 'В продаже'), ('sold', 'Продан')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
