# Generated by Django 5.2.8 on 2025-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_car_in_stock_alter_car_status_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='status_car',
        ),
        migrations.AddField(
            model_name='car',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='В продаже'),
        ),
        migrations.AddField(
            model_name='car',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='car',
            name='in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
